### PR TITLE
master branch doesn't exist

### PR DESCRIPTION
**Pull request by Mte90**
So this creates errors in GH action :-)

### CODE REVIEW

**Comment by jeffpaul** [comment]
@dinhtungdu I think this is probably best replaced with `stable` yeah?

**Comment by dinhtungdu** [comment]
> @dinhtungdu I think this is probably best replaced with `stable` yeah?

Yeah. I agree. @Mte90 Thanks so much for the PR! Can you please update it to use `stable`?

**Comment by Mte90** [comment]
Done :-)

**Review by dinhtungdu — APPROVED** [review]
@Mte90 Thank you so much!

**Pull request merged**
